language: rust
sudo: false
cache: cargo

os:
- linux
- osx

# Set global environment only
env:
  global:
  - RUST_BACKTRACE=1

notifications:
  email:
    on_success: never

matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly

  include:
  - name: 'Rust: format check'
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt --verbose --all -- --check

  - name: 'Rust: style check'
    if: env(ENABLE_CLIPPY) = 1
    install:
    - rustup component add clippy
    script:
    - cargo clippy --verbose --all -- -D warnings

  - name: 'Rust: code coverage'
    os: linux
    install:
    - cargo install cargo-tarpaulin
    script:
    - cargo tarpaulin --verbose --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
