name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Code Coverage
      # You may pin to the exact commit or the version.
      # uses: actions-rs/tarpaulin@60f0b12e5beec09ccca51758913f82d01889151c
      uses: actions-rs/tarpaulin@v0.1.0
      env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      with:
        # Extra command line arguments passed to cargo-tarpaulin
        args: '--coveralls $COVERALLS_TOKEN'
        out-type: Lcov
