name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin 
    - name: Code Coverage
      env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: cargo tarpaulin -v --coveralls $COVERALLS_TOKEN
